val optim_for_size : 'a -> bool
val propagate_float_constants : 'a -> bool
val generate_float_constants : 'a -> bool
val va_strict : 'a -> bool
val optim_tailcalls : 'a -> bool
val optim_constprop : 'a -> bool
val optim_CSE : 'a -> bool
val optim_redundancy : 'a -> bool
val debug : 'a -> bool
